0.01::aNAPHYLAXIS.
0.1::dISCONNECT.
0.04::kINKEDTUBE.
0.1::iNSUFFANESTH.
0.05::fIO2("LOW"); 0.95::fIO2("NORMAL").
0.92::iNTUBATION("NORMAL"); 0.03::iNTUBATION("ESOPHAGEAL"); 0.05::iNTUBATION("ONESIDED").
0.05::mINVOLSET("LOW"); 0.9::mINVOLSET("NORMAL"); 0.05::mINVOLSET("HIGH").
0.05::eRRLOWOUTPUT.
0.2::hYPOVOLEMIA.
0.01::pULMEMBOLUS.
0.05::lVFAILURE.
0.1::eRRCAUTER.
0.95::lVEDVOLUME("LOW"); 0.04::lVEDVOLUME("NORMAL"); 0.01::lVEDVOLUME("HIGH") :- hYPOVOLEMIA, lVFAILURE.
0.01::lVEDVOLUME("LOW"); 0.09::lVEDVOLUME("NORMAL"); 0.9::lVEDVOLUME("HIGH") :- hYPOVOLEMIA, \+lVFAILURE.
0.98::lVEDVOLUME("LOW"); 0.01::lVEDVOLUME("NORMAL"); 0.01::lVEDVOLUME("HIGH") :- \+hYPOVOLEMIA, lVFAILURE.
0.05::lVEDVOLUME("LOW"); 0.9::lVEDVOLUME("NORMAL"); 0.05::lVEDVOLUME("HIGH") :- \+hYPOVOLEMIA, \+lVFAILURE.
0.98::tPR("LOW"); 0.01::tPR("NORMAL"); 0.01::tPR("HIGH") :- aNAPHYLAXIS.
0.3::tPR("LOW"); 0.4::tPR("NORMAL"); 0.3::tPR("HIGH") :- \+aNAPHYLAXIS.
0.01::pAP("LOW"); 0.19::pAP("NORMAL"); 0.8::pAP("HIGH") :- pULMEMBOLUS.
0.05::pAP("LOW"); 0.9::pAP("NORMAL"); 0.05::pAP("HIGH") :- \+pULMEMBOLUS.
0.98::sTROKEVOLUME("LOW"); 0.01::sTROKEVOLUME("NORMAL"); 0.01::sTROKEVOLUME("HIGH") :- hYPOVOLEMIA, lVFAILURE.
0.5::sTROKEVOLUME("LOW"); 0.49::sTROKEVOLUME("NORMAL"); 0.01::sTROKEVOLUME("HIGH") :- hYPOVOLEMIA, \+lVFAILURE.
0.95::sTROKEVOLUME("LOW"); 0.04::sTROKEVOLUME("NORMAL"); 0.01::sTROKEVOLUME("HIGH") :- \+hYPOVOLEMIA, lVFAILURE.
0.05::sTROKEVOLUME("LOW"); 0.9::sTROKEVOLUME("NORMAL"); 0.05::sTROKEVOLUME("HIGH") :- \+hYPOVOLEMIA, \+lVFAILURE.
0.9::hISTORY :- lVFAILURE.
0.01::hISTORY :- \+lVFAILURE.
0.1::sHUNT("NORMAL"); 0.9::sHUNT("HIGH") :- iNTUBATION("NORMAL"), pULMEMBOLUS.
0.95::sHUNT("NORMAL"); 0.05::sHUNT("HIGH") :- iNTUBATION("NORMAL"), \+pULMEMBOLUS.
0.1::sHUNT("NORMAL"); 0.9::sHUNT("HIGH") :- iNTUBATION("ESOPHAGEAL"), pULMEMBOLUS.
0.95::sHUNT("NORMAL"); 0.05::sHUNT("HIGH") :- iNTUBATION("ESOPHAGEAL"), \+pULMEMBOLUS.
0.01::sHUNT("NORMAL"); 0.99::sHUNT("HIGH") :- iNTUBATION("ONESIDED"), pULMEMBOLUS.
0.05::sHUNT("NORMAL"); 0.95::sHUNT("HIGH") :- iNTUBATION("ONESIDED"), \+pULMEMBOLUS.
0.05::vENTMACH("ZERO"); 0.93::vENTMACH("LOW"); 0.01::vENTMACH("NORMAL"); 0.01::vENTMACH("HIGH") :- mINVOLSET("LOW").
0.05::vENTMACH("ZERO"); 0.01::vENTMACH("LOW"); 0.93::vENTMACH("NORMAL"); 0.01::vENTMACH("HIGH") :- mINVOLSET("NORMAL").
0.05::vENTMACH("ZERO"); 0.01::vENTMACH("LOW"); 0.01::vENTMACH("NORMAL"); 0.93::vENTMACH("HIGH") :- mINVOLSET("HIGH").
0.95::cVP("LOW"); 0.04::cVP("NORMAL"); 0.01::cVP("HIGH") :- lVEDVOLUME("LOW").
0.04::cVP("LOW"); 0.95::cVP("NORMAL"); 0.01::cVP("HIGH") :- lVEDVOLUME("NORMAL").
0.01::cVP("LOW"); 0.29::cVP("NORMAL"); 0.7::cVP("HIGH") :- lVEDVOLUME("HIGH").
0.95::pCWP("LOW"); 0.04::pCWP("NORMAL"); 0.01::pCWP("HIGH") :- lVEDVOLUME("LOW").
0.04::pCWP("LOW"); 0.95::pCWP("NORMAL"); 0.01::pCWP("HIGH") :- lVEDVOLUME("NORMAL").
0.01::pCWP("LOW"); 0.04::pCWP("NORMAL"); 0.95::pCWP("HIGH") :- lVEDVOLUME("HIGH").


query(aNAPHYLAXIS).
query(dISCONNECT).
query(kINKEDTUBE).
query(iNSUFFANESTH).
query(fIO2("LOW")).
query(fIO2("NORMAL")).
query(iNTUBATION("NORMAL")).
query(iNTUBATION("ESOPHAGEAL")).
query(iNTUBATION("ONESIDED")).
query(mINVOLSET("LOW")).
query(mINVOLSET("NORMAL")).
query(mINVOLSET("HIGH")).
query(eRRLOWOUTPUT).
query(hYPOVOLEMIA).
query(pULMEMBOLUS).
query(lVFAILURE).
query(eRRCAUTER).
query(lVEDVOLUME("LOW")).
query(lVEDVOLUME("NORMAL")).
query(lVEDVOLUME("HIGH")).
query(tPR("LOW")).
query(tPR("NORMAL")).
query(tPR("HIGH")).
query(pAP("LOW")).
query(pAP("NORMAL")).
query(pAP("HIGH")).
query(sTROKEVOLUME("LOW")).
query(sTROKEVOLUME("NORMAL")).
query(sTROKEVOLUME("HIGH")).
query(hISTORY).
query(sHUNT("NORMAL")).
query(sHUNT("HIGH")).
query(vENTMACH("ZERO")).
query(vENTMACH("LOW")).
query(vENTMACH("NORMAL")).
query(vENTMACH("HIGH")).
query(cVP("LOW")).
query(cVP("NORMAL")).
query(cVP("HIGH")).
query(pCWP("LOW")).
query(pCWP("NORMAL")).
query(pCWP("HIGH")).